/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisiwa;
import java.sql.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class presensi2 extends javax.swing.JFrame {
    String kodematkul,nip,nama;
    int a;
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    int pertemuan,jmlhmhs;
    int i=0;
    
    /**
     * Creates new form presensi2
     */
    public presensi2(String kodematkul,int jmlhmhs,int pertemuan,String nip, String nama) {
        initComponents();
        this.pertemuan = pertemuan;
        this.nip = nip;
        this.nama = nama;
        this.jmlhmhs = jmlhmhs;
        this.kodematkul=kodematkul;
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        start(this.kodematkul);
        
    }
        
        
        public void start (String kodematkul){
        String a,b;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            sql= "SELECT mhs_nim,mhs_nama FROM presensi WHERE kodematkul='"+kodematkul+"'";
            rs = stat.executeQuery(sql);
            while (rs.next()){
              a = rs.getString("mhs_nim");
              b = rs.getString("mhs_nama");
              i=i+1;
              model.addRow(new Object[]{b,a});}
                
                
            }
            
         catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 200));
        setSize(new java.awt.Dimension(400, 200));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAMA", "NIM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 370, 90);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 30, 230, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 80, 230, 30);

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 140, 100, 30);

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 140, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisiwaJPEG/PRESENSI2.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 200);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String A,B;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         int selRow = jTable1.getSelectedRow();
         Object value = jTable1.getValueAt(selRow, 1);
         A= value.toString();
         
        try { //nim , kode matkul, nama
            sql = "UPDATE presensi SET kehadiran_"+pertemuan+"=1 WHERE mhs_nim ='"+A+"'";
            System.out.println(sql);
            stat.executeUpdate(sql);
            int row = jTable1.getSelectedRow();
            if(row>=0){
                      model.removeRow(row);
                      int rowtot = jTable1.getRowCount();
                   if (rowtot <=0){   
                   JOptionPane.showMessageDialog(null,"Presensi Berhasil");
                   presensi mauslesai = new presensi (nip,nama);
                   mauslesai.setVisible(true);
                   this.dispose();
                   }
            }
            /*if(rs.next()){
        
                    JOptionPane.showMessageDialog(null, "berhasil Registerasi");
                
            }else{
                    JOptionPane.showMessageDialog(null, "username atau password tidak terimput");
                }*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    String A,B;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         int selRow = jTable1.getSelectedRow();
         Object value = jTable1.getValueAt(selRow, 1);
         A= value.toString();
         
        try { //nim , kode matkul, nama
            sql = "UPDATE presensi SET kehadiran_"+pertemuan+"=0 WHERE mhs_nim ='"+A+"'";
            System.out.println(sql);
            stat.executeUpdate(sql);
            int row = jTable1.getSelectedRow();          
                 if(row>=0){
                      model.removeRow(row);
                      int rowtot = jTable1.getRowCount();
                   if (rowtot <=0){   
                   JOptionPane.showMessageDialog(null,"Presensi Berhasil");
                   presensi mauslesai = new presensi (nip,nama);
                   mauslesai.setVisible(true);
                   this.dispose();
                 
            
                 }
                 }
            /*if(rs.next()){
        
                    JOptionPane.showMessageDialog(null, "berhasil Registerasi");
                
            }else{
                    JOptionPane.showMessageDialog(null, "username atau password tidak terimput");
                }*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
