/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisiwa;
import java.sql.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author user
 */
public class presensi extends javax.swing.JFrame {
    String NIP,nama;
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    String matkulfinal;
    
    /**
     * Creates new form presensi
     */
    public presensi(String NIP,String nama) {
        this.NIP = NIP;
        this.nama = nama;
        initComponents();
        jLabel4.setText(nama);
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        Filecombo();
        
    }
    
 
    
   
    
    
    
    void filterhuruf(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom Jumlah Hanya Bisa Memasukan Karakter Angka");
        }}
     void filterspasi(KeyEvent a){
        if(Character.isSpace(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom Jumlah Hanya Bisa Memasukan Karakter Angka");
        }}
     
    private void Filecombo(){
        
        try {
            sql= "SELECT * FROM matkul WHERE dsn_nip ='"+NIP+"';";
            rs = stat.executeQuery(sql);
            while (rs.next()){
                String kodematkul = rs.getString("kodematkul");
                matkulnya.addItem(kodematkul); 
            }
           
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    public int checkermhs (String kodematkul){
       int jmlh=0;
        try {
            sql= "SELECT mhs_nim FROM presensi WHERE kodematkul ='"+kodematkul+"';";
            rs = stat.executeQuery(sql);
            while (rs.next()){
                jmlh=jmlh+1;
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        return jmlh ;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        matkulnya = new javax.swing.JComboBox();
        pertemuannya = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 800));
        setSize(new java.awt.Dimension(700, 800));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 190, 220, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Pertemuan ke : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 320, 120, 30);

        jButton2.setText("Rekap Presensi");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 170, 150, 60);

        jButton1.setText("MULAI PRESENSI");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 420, 190, 50);

        matkulnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matkulnyaActionPerformed(evt);
            }
        });
        getContentPane().add(matkulnya);
        matkulnya.setBounds(0, 240, 230, 30);

        pertemuannya.setBackground(new java.awt.Color(255, 255, 0));
        pertemuannya.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pertemuannya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pertemuannyaActionPerformed(evt);
            }
        });
        pertemuannya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pertemuannyaKeyTyped(evt);
            }
        });
        getContentPane().add(pertemuannya);
        pertemuannya.setBounds(150, 320, 230, 30);

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(401, 90, 230, 40);

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(651, 16, 30, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisiwaJPEG/presensi.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
     this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        inputmatkul A = new inputmatkul(this.NIP,this.nama);
        A.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jLabel3MouseClicked

    private void matkulnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matkulnyaActionPerformed
      String A = (String) matkulnya.getSelectedItem();
        this.matkulfinal = A;
        
        // TODO add your handling code here:
    }//GEN-LAST:event_matkulnyaActionPerformed

    private void pertemuannyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pertemuannyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pertemuannyaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pertemuannyaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pertemuannyaKeyTyped
        filterhuruf(evt); 
        filterspasi(evt);// TODO add your handling code here:
    }//GEN-LAST:event_pertemuannyaKeyTyped

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String a = pertemuannya.getText();
        int angka3 = Integer.valueOf(a);
        String b = matkulfinal;
        String name=null,kodematkul=null;
        if (angka3 <= 20 ){
            try {
            sql= "SELECT * FROM matkul WHERE kodematkul ='"+b+"';";
            rs = stat.executeQuery(sql);
            while (rs.next()){
                name = rs.getString("matkul");
                kodematkul = rs.getString("kodematkul");  
            }
           int jmlhmhsnya = checkermhs(kodematkul);
           presensi2 A = new presensi2 (kodematkul,jmlhmhsnya,angka3,NIP,nama);
           A.setVisible(true);
           this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }   
        else{
               JOptionPane.showMessageDialog(null,"Pertemuan maksimal hanya 20x"); 
                }
        
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        rekap a = new rekap (matkulfinal,NIP,nama);
        a.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    
            
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox matkulnya;
    private javax.swing.JTextField pertemuannya;
    // End of variables declaration//GEN-END:variables
}
