/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisiwa;
import java.awt.BorderLayout;
import java.awt.GridLayout;

import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import java.sql.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
/**
 *
 * @author user
 */
public class rekap extends javax.swing.JFrame {
    JScrollPane scrollpane;
    String matakuliah;
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    String NIP,nama;
 
    
    /**
     * Creates new form rekap
     */
    public rekap(String matkulfinal,String NIP,String nama) {
        this.matakuliah=matkulfinal;
        this.NIP=NIP;
        this.nama=nama;
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        initComponents();
        lebarkolom();
        namamatkulnya(matakuliah);
        start(matkulfinal);
    }
    public void lebarkolom(){
        TableColumn column; 
      jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
      
     column = jTable2.getColumnModel().getColumn(0);
     column.setPreferredWidth(110);
      
    }
    
    
    public void start (String kodematkul){
        String a,b;
        String[] p = new String[20];
        int jumlahpertemuan;
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        try {
            sql= "SELECT * FROM presensi WHERE kodematkul='"+matakuliah+"'";
            rs = stat.executeQuery(sql);
            while (rs.next()){
              a = rs.getString("mhs_nim");
              b = rs.getString("mhs_nama");
              jumlahpertemuan=0;
              
              
              while (jumlahpertemuan <20){
                  int temp = jumlahpertemuan+1;
                  p[jumlahpertemuan] = rs.getString("kehadiran_"+temp);
                  
                  if (p[jumlahpertemuan].equals("0")){
                      p[jumlahpertemuan]= "tidak hadir";
                  }
                  else  {
                      System.out.println(p[jumlahpertemuan]);
                      p[jumlahpertemuan]="hadir";
                  }
                  jumlahpertemuan = jumlahpertemuan+1;
              }
                System.out.println("udah sampai ");
              model.addRow(new Object[]{b,a,p[0],p[1],p[2],p[3],p[4],p[5],p[6],p[7],p[8],p[9],p[10],p[11],p[12],p[13],p[14],p[15],p[16],p[17],p[18],p[19]});
            
            
            
            }
                
                
            }
            
         catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void namamatkulnya(String matkulfinalnya){
        String a=null;
        try {
            sql= "SELECT matkul from matkul where kodematkul ='"+matkulfinalnya+"'";
            rs = stat.executeQuery(sql);
           
            while (rs.next()){
              a = rs.getString("matkul");      
                
            }
        }  
         catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        jLabel3.setText(a);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 800));
        setSize(new java.awt.Dimension(700, 800));
        getContentPane().setLayout(null);

        jButton1.setText("KEMBALI");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 20, 110, 25);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "NIM", "Pertemuan 1", "Pertemuan 2", "Pertemuan 3", "Pertemuan 4", "Pertemuan 5", "Pertemuan 6", "Pertemuan 7", "Pertemuan 8", "Pertemuan 9", "Pertemuan 10", "Pertemuan 11", "Pertemuan 12", "Pertemuan 13", "Pertemuan 14", "Pertemuan 15", "Pertemuan 16", "Pertemuan 17", "Pertemuan 18", "Pertemuan 19", "Pertemuan 20"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 210, 680, 580);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 110, 230, 40);

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(650, 10, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisiwaJPEG/rekappresensi.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -4, 700, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       presensi a = new presensi(NIP,nama);
       a.setVisible(true);
       this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
